### ISSUE TITLE
Is layer shell protocol supported on KDE?

### ISSUE THREAD

**Issue by hamza-Algohary** [wmww/gtk-layer-shell#127]
The readme mentions that wlroots and mir compositors support layer shell, and gnome's Wayland does not support it, but it doesn't mention anything about KDE.

**Comment by wmww** [comment]
I do not know. Some searching makes it appear it might, but mostly I'm just seeing a Qt client library rather than anything conclusive about server support. I'm not going to install and play with plasma right now, but if someone else wants to please report back if it works and I'll add it to the readme.

**Comment by ids1024** [comment]
Yes, layer shell support was added to KWin somewhat recently: https://invent.kde.org/plasma/kwin/-/merge_requests/202

KDE was using it's own protocol for something similar, but is moving over to the standard layer shell protocol, assuming they haven't finished doing that yet.
