### ISSUE TITLE
Discussion: A GTK Picture-in-Picture shell library

### ISSUE THREAD

**Issue by davidedmundson** [wmww/gtk-layer-shell#151]
A proposal for PIP shell exists here:
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/132

We need some client implementations so I made a GTK library here: https://github.com/davidedmundson/gtk-pip-shell

and then added that into Firefox:
![image](https://user-images.githubusercontent.com/2776077/227930215-75bd963f-695d-4aa9-ad09-d52d05d5f2bf.png)

and can confirm it works nicely.

The work is extremely heavily influenced by the code here. 

It needs all sorts of cleanup and polishing before it could be released for actual usage. I'm not a GTK dev so it needs some review by someone more experienced when it's ready. Mostly I wanted to get some discussion going about direction in particular the duplication of `gtk-priv` which is non trivial code. 

Is a single repo of "GTK shells" an idea worth considering?

**Comment by wmww** [comment]
Following up on this, as per https://github.com/wmww/gtk-layer-shell/issues/37#issuecomment-1498783317 I'm actively working on GTK4 support for layer shell. The approach I'm taking of wrapping libwayland calls has turned out to be quite a bit simpler than gtk-priv, and I recommend it if there isn't a better alternative. It should work with both GTK3 and GTK4. There's potential for creating a library to do this we both could use, though I won't put effort towards that until after GTK4 Layer Shell is working and released.

**Comment by davidedmundson** [comment]
Thanks for following up. The approach certainly looks creative. 
Don't rush on a library, I need to fight upstream protocols first.
