### ISSUE TITLE
Moving away from GitHub

### ISSUE THREAD

**Issue by oifj34f34f** [wmww/gtk-layer-shell#152]
Github is

- Proprietary
- Microsoft-owned
- [GitHub Copilot™ attacks copyleft licensing](https://nogithub.codeberg.page/)

I would recommend Codeberg or SourceHut, they are open source.

**Comment by wmww** [comment]
Many ideological and pragmatic arguments can be made on the merits of different platforms. I personally use one the alternatives you mentioned for most of my new projects. That being said, GTK Layer Shell has been on GH since it was created and will not be changing services without an urgent, concrete reason. I'm sorry you don't like this service. You are welcome to not contribute to or use GTK Layer Shell for that reason if you so desire.
