### ISSUE TITLE
`.get_zwlr_layer_surface_v1(window)` returns integer `0`

### ISSUE THREAD

**Issue by jeLee6gi** [wmww/gtk-layer-shell#196]
I am using the Python bindings and `.get_zwlr_layer_surface_v1(window)` does not work as I expect it to. According to the docs it should return `None` or the Wayland layer but for me it always returns `0`

MWE using the example from this repo (returns `<class 'int'> 0` for me)

```python
import gi
gi.require_version('Gtk', '3.0')

try:
    gi.require_version('GtkLayerShell', '0.1')
except ValueError:
    import sys
    raise RuntimeError('\n\n' +
        'If you haven\'t installed GTK Layer Shell, you need to point Python to the\n' +
        'library by setting GI_TYPELIB_PATH and LD_LIBRARY_PATH to <build-dir>/src/.\n' +
        'For example you might need to run:\n\n' +
        'GI_TYPELIB_PATH=build/src LD_LIBRARY_PATH=build/src python3 ' + ' '.join(sys.argv))

from gi.repository import Gtk, GtkLayerShell

window = Gtk.Window()
label = Gtk.Label(label='GTK Layer Shell with Python!')
window.add(label)

GtkLayerShell.init_for_window(window)
GtkLayerShell.auto_exclusive_zone_enable(window)
GtkLayerShell.set_margin(window, GtkLayerShell.Edge.TOP, 10)
GtkLayerShell.set_margin(window, GtkLayerShell.Edge.BOTTOM, 10)
GtkLayerShell.set_anchor(window, GtkLayerShell.Edge.BOTTOM, 1)
layer = GtkLayerShell.get_zwlr_layer_surface_v1(window)
print(type(layer), layer)

window.show_all()
window.connect('destroy', Gtk.main_quit)
Gtk.main()
```

Let me know if you cannot reproduce and need more information.

**Comment by wmww** [comment]
It looks like there's two things going on:
1. It returns a pointer to the Wayland protocol object for the window (as [documented](https://wmww.github.io/gtk-layer-shell/gtk-layer-shell-Gtk-Layer-Shell.html#gtk-layer-get-zwlr-layer-surface-v1)), however it seems there isn't a good Python representation for this pointer so the bindings are converting it to an int (0 for null or a large number for a valid memory address)
2. You're calling `.get_zwlr_layer_surface_v1()` before the window is shown, which is why you're getting null (0). If you make the call after `window.show_all()` it returns a non-zero number

I'm not sure what you're trying to do. This isn't a typical function to call, and it's unclear how you could correctly use it from Python. The conversion to int in the bindings is a little strange, but I think it's basically working as intended.

**Comment by jeLee6gi** [comment]
Gotcha, it makes sense to me now, thank you for the clarification!
