### ISSUE TITLE
Upstream integration of the gtk-layer-shell?

### ISSUE THREAD

**Issue by rubyFeedback** [wmww/gtk-layer-shell#35]
Hey there,

Do you think gtk-layer-shell could be integrated into wayland-protocols or wayland?

https://wayland.freedesktop.org/releases/wayland-protocols-1.20.tar.xz
https://wayland.freedesktop.org/releases/wayland-1.18.0.tar.xz

Explanation: Recently I had a configure-related problem with one of the mate-desktop
components (I think); in the sense that one component wanted --enable-wayland.

Then the message was something along the lines of needing the gtk-layer-shell.
This is how I found the project here actually.

I am thinking of a configure flag, like in wayland-protocols or wayland, to
enable gtk:

    --enable-gtk # or --enable-gtk3, you get the point

Or perhaps --enable-gtk-layer-shell or something along the lines.

Why would I suggest integration? This is mostly from the user's point of
view of convenience e. g. if we wish to compile this, then it would be
more convenient to have it integrated upstream in "one go", one
package.

In the last 2 months or so I saw a sudden increase in wayland-specific
stuff. I am still on xorg/x11 myself but the smoother everything in the
ecosystem may be, the simpler it may be for me - so ultimately this
suggestion is also a bit selfish I suppose. :)

Feel free to close this issue here for any reason, in particular if it
is not applicable or would take too much time.

**Comment by wmww** [comment]
This doesn't make sense for two reasons:
- Toolkit-specific integration is very much out-of-scope for libwayland
- The layer shell protocol itself is not a core Wayland protocol

Upstreaming this library into GTK is a more reasonable idea, but that's also not going to happen. I'm having trouble getting the API I need into GTK4, much less a whole Layer Shell implementation into GTK3 (which isn't even getting new features at the moment).

> Why would I suggest integration? This is mostly from the user's point of view of convenience

Normal users generally don't compile software, and if you're a developer you should be able to manage installing a library. Nice people have kindly packaged GTK Layer Shell for Ubuntu and Fedora, so on the latest version of both distros you can simply run `apt install [https://packages.ubuntu.com/source/focal/gtk-layer-shell](libgtk-layer-shell-dev)`/`dnf install gtk-layer-shell-devel` and your problem is solved. If you're on a different distro, you can simply clone this repo and build/install from the instructions in the readme.

**Comment by wmww** [comment]
I've now added to the repo a list of distros GTK Layer Shell is packaged for

**Comment by AdrianVovk** [comment]
@wmww Will this library be impossible on GTK4 then since you don't have the needed API?

**Comment by wmww** [comment]
It's complicated. It depends on how the platform code in GTK4 ends up looking when all the dust settles, and what, if anything, I manage to get added. We'll see.

**Comment by AdrianVovk** [comment]
@wmww If you need any backup upstream (like to prove the interest in the API) I'd be happy to help!
