### ISSUE TITLE
(not so) harmless "Couldn't map window as subsurface" warning

### ISSUE THREAD

**Issue by wmww** [wmww/gtk-layer-shell#38]
When some popups appear (such as tooltips), the following warning is shown:
```
(gtk-layer-demo:143889): Gdk-WARNING **: 15:30:45.911: Couldn't map window 0x55e39f0aa030 as subsurface because its parent is not mapped.
```
I believe this to be a harmless GTK bug (there's a lot of questionable logic around custom surfaces). Considering it's not causing any other problems, it's not worth trying to fix at this time.

**Comment by wmww** [comment]
It doesn't seem to happen with my Ubuntu 20.04 system GTK. Might have been introduced in GTK v3.24.21

**Comment by Java-boi** [comment]
I think this bug is what's causing an issue in the waybar project. https://github.com/Alexays/Waybar/issues/859

**Comment by wmww** [comment]
Unlikely. It really is harmless (AFAIK)

**Comment by wb9688** [comment]
In [my very WIP (e.g. multi-monitor isn't supported yet) port of PCManFM's desktop manager to Wayland](https://github.com/wb9688/pcmanfm/tree/gtk-layer-shell) using GTK Layer Shell, I'm getting `(pcmanfm:14934): Gdk-WARNING **: 11:38:54.363: Couldn't map window 0x5555555b6ad0 as subsurface because its parent is not mapped.` and I'm getting a normal window with SSD, while without GTK Layer Shell I'm not getting that warning and it's positioned correctly and doesn't have a SS
D.

You could reproduce this by compiling it yourself (preferably in combination with [my fork of LibFM](https://github.com/wb9688/libfm/tree/wb9688)), starting it with `pcmanfm --desktop`, focusing the desktop, pressing some key to start the "search". GTK Layer Shell could be disabled by uncommenting [these lines](https://github.com/wb9688/pcmanfm/blob/gtk-layer-shell/src/desktop.c#L4779-L4788), then it'll just show up as a normal window.

When I add a `return TRUE;` at https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gdk/wayland/gdkwindow-wayland.c#L3036, it is positioned correctly though (but keyboard input doesn't work, maybe I just have to disable keyboard interactivity as long as `search_window` is visible?), so it seems like GTK just thinks GTK Layer Shell windows aren't mapped for some reason.

**Comment by wmww** [comment]
All right, so my assessment is this warning is usually harmless, but in some cases (such as yours) it's possible to create a subsurface that actually fails to map property. Can you point me to where in your pcmanfm fork the troublesome search box subsurface is created? I'll want to write an [integration test](https://github.com/wmww/gtk-layer-shell/tree/master/test/integration-tests) with a minimal example of this behavior so once it's fixed it stays fixed.

**Comment by wb9688** [comment]
`search_window` is created around https://github.com/wb9688/pcmanfm/blob/gtk-layer-shell/src/desktop.c#L3824

However if I understand the GTK code I linked in my previous comment correctly, it thinks the parent (i.e. my full-screen GTK Layer Shell window) is not mapped. Like I said, if I change it so that it returns true even if the parent isn't mapped (for testing purposes, normally that wouldn't be a good idea of course), it's able to correctly map the `search_window` as a subsurface.

Thanks for looking into it!

**Comment by wmww** [comment]
With that code sample the issue was easy to reproduce, and with just one more `gtk-priv` call it's fixed. PR incoming.
