### ISSUE TITLE
Popover flickers on mouse move

### ISSUE THREAD

**Issue by psnszsn** [wmww/gtk-layer-shell#47]
After doing something that should visually change the contents of a popover, it does not immediately change, but instead it starts flickering between the new and the old "frame" when moving the mouse.

This can be observed in the demo after clicking the plus/minus buttons of the "Set margin" popover.

**Comment by wmww** [comment]
Thanks for noticing this. It seems to effect Sway but not Mir. This doesn't necessarily indicate it's a sway bug (Mir ignores surface damage, so that's likely involved). Considering #51 GTK Layer Shell is definitely doing *something* wrong.

**Comment by wmww** [comment]
In my testing the problem goes away when we use a custom XDG toplevel implementation in place of our Layer Shell one. This is a strong indicator to me the bug may be on the Sway/wlroots side. Unfortunately the only other Layer shell supporting compositor I have to test with is Mir, and Mir completely ignores damage (so I'm not surprised it works on Mir, even if the bug is on the client side).

I want to actually find the bug before yeeting this issue at wlroots. This might go dead for a couple days as I've got other things to do, but I'll be back.

**Comment by wmww** [comment]
Closing, as this is a bug in Sway
