### ISSUE TITLE
Cannot set both exclusize zone and anchor in 2 edges.

### ISSUE THREAD

**Issue by rilian-la-te** [wmww/gtk-layer-shell#67]
I want to set both exclusize zone and anchor to top-left. How to do it?

**Comment by ammen99** [comment]
Setting exclusive zone does not make any sense if you are anchored to only 2 edges, because the compositor cannot know which edge you want to reserve space from. You need to achor to 1 or 3 edges for exclusive zone to make sense.

**Comment by rilian-la-te** [comment]
@ammen99 I want to do like this:
(panel in top-left) - (exclusive zone in top)
(panel in left-top) - (exclusive zone in left)

It should depend on where window is smaller.
If I anchored to 1 or 3 edges, window will be in center, which I do not want.

**Comment by wmww** [comment]
Hello! Unfortunately, there's not much I can do. This issue is with the layer shell protocol which is controlled by the wlroots developers, not me. You've got two options:
- Propose protocol modifications upstream
- Find a workaround
I would guess getting this *corner case* (sorry, had to) added to the protocol is unlikely to happen, at least not unless there were multiple other users who wanted the same thing. I'm going to focus on workarounds.

The most obvious is to make two layer surface windows. One with your panel's content and anchored to the corner, and the other transparent, anchored to the side and with the exclusive zone you want. You can make a window transparent with `gtk_widget_set_opacity(window, 0.0)`. You may want to connect your main window's `size_allocate` signal to a function that sets the empty window's exclusive zone.

The other way I can think of is anchoring to 3 edges and using a very large margin to make it look like it's in one corner. Getting the logic right here might be tricky, so I wouldn't prefer this method.

**Comment by rilian-la-te** [comment]
@wmww this is not about adding this to protocol, this is about layer-shell request.
How I see it in layer-shell? if window has auto_exclusive_zone and anchored to 2 edges, then:
1. get_preferred_size of widget
2. check, which is smaller
3. set exclusive zone for this edge.

Or you means than it is not possible for protocol to have such exclusive zone?

**Comment by wmww** [comment]
> Or you means than it is not possible for protocol to have such exclusive zone?

[Correct](https://github.com/swaywm/wlr-protocols/blob/50f3a8d3c882924afa5d2569c4eb44e636703fb4/unstable/wlr-layer-shell-unstable-v1.xml#L159). The protocol doesn't allow setting an exclusive zone for a particular edge, the edge is implied by the surface's anchor. The GTK Layer Shell API maps quite closely to the wlr-layer-shell Wayland protocol. The biggest difference is that GTK Layer Shell will automatically change the exclusive zone as the window size changes if auto exclusive zone is enabled (but you can still set exclusive zone manually if you want).
