### ISSUE TITLE
Popups do not grab

### ISSUE THREAD

**Issue by wmww** [wmww/gtk-layer-shell#9]
Layer popups do not send the "grab" request, even when normal GTK ones do.

**Comment by alebastr** [comment]
As I figured out, this requires calling `xdg_popup_grab` with wl_seat and last event serial.

Both of these parameters are hidden deep in gdk internals and require some non-trivial effort to obtain (with wl_seat it's more a matter of 'does this surface have a grab?' because seat is the same for the whole app). I had to redeclare private struct definitions for `GdkWindowImplWayland` and most of the input events and copy `find_grab_input_seat` and  `_gdk_wayland_seat_get_last_implicit_grab_serial` to make grab requests work. Obviously, this raises licensing and maintenance concerns.

Although it might be possible to recreate event and grab tracking code independently, given that all wl_* objects are available from gdk.

**Comment by wmww** [comment]
There actually may be a way to solve this, but it's a fundamentally different approach to how the library works now. Getting the `wl_seat` is trivial (...), but I determined pulling the serial out of GTK is a lot cause (recall you need to send the correct serial to `xdg_popup_grab`). Also the logic to determine when to grab, is something I don't want to try to replicate.

The solution would be to make GTK manger popups. Man-in-the-middling GTK's internal virtual dispatch is something I already do, and if I intercept the right function call I should be able to do some fuckery that creates a layer shell popup managed by GTK.

I'm not going to do this right now, because my priority is getting patches into GTK4 that will allow this sort of thing to be done properly. Once that's done (will probably be on the order of weeks or longer) we can think about back porting it into GTK3, or hacking more features into gtk-layer-shell.

Also I'm traveling and haven't been working on much of anything very fast ¯\_(ツ)_/¯

If you're interested in helping out with any of these efforts (especially the GTK4 patches), message me (matrix: @wmww:matrix.org, freenode: wmww, email: wm@wmww.sh)

**Comment by alebastr** [comment]
Oh, it's been almost a year. I guess I'll post another portion of random thoughts :smile:.

For a while I've been using this patch: https://github.com/alebastr/gtk-layer-shell/compare/master...xdg-popup-grab-hack. It does the exact thing I described in my previous comment -- copies the LGPL2+ code from GTK3 to access some private fields. I haven't encountered any problems so far (except the whole "copy LGPL2+ code" thing).

There's too many private fields and static functions in GtkWayland and I wasn't able to make any improvements on this patch since December. And yes, the same private static function `gdk_wayland_window_create_xdg_popup` assigns the role to the surface (which would fail since it's already layer surface popup) and sets grab. There's nothing to intercept with virtual dispatch and no way to make it handle custom surface :scream:.

Another amusing thing is that  wlroots in fact does not care about serial at all. I.e. `xdg_popup_grab (self->xdg_popup, seat, 0);` would make things work for all wlroots-based compositors for now. A downside of this "solution" is that the compositor has a right to immediately dismiss the popup with an incorrect grab serial and would start doing that as soon as the validation of `serial` is implemented in wlroots.
***
I did not get to GTK4 patches, however the upstream codebase seems to be changing too fast (your patches from March are already conflicting with GTK master). I'll try to look into that when I have time, but no promises.
I wonder if it's possible to take inspiration from Qt wayland shell plugin API and make GTK work similarly...

**Comment by wmww** [comment]
I don't disagree with anything you said. I'm going to take another look at GTK4 at some point. They didn't like my architecture, but it might be possible to add on to the architecture they're moving towards. As for making it work on GTK3, I see two main issues:

## Licensing
If it comes down to just a licensing problem, we can work it out. As a last resort, we can just GPL this whole project. Making it work is probably worth it.

However, ideally we'd find a way to keep all of our work legally separated from the MIT stuff. The resulting library would be LGPL, but you could fork the project without the LGPL bits as MIT, or use peaces of it under MIT. I need to look more into if this is possible.

## Fragility
I'm concerned with completely falling over when GTK slightly changes it's internal structures. I've got some ideas about auto-downloading multiple versions of the GTK files we need during the build process, and then dynamically using them. Not sure if this is actually necessary.

How big of a problem is this bug for devs/users? I'm doing a number of things right now, but if it's a real pain for multiple people I can try to prioritize it.

**Comment by wmww** [comment]
As for the licensing concern, it appears we can LGPL the while project, and then give every non-GTK file an explicit MIT license: https://www.softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html#x1-50002.3. This is mildly annoying, but seems like a reasonable approach.

**Comment by alebastr** [comment]
#### Licensing
I guess you got that covered.
Reading LGPLv2 makes me think that only files derived from the original LGPL source should be kept under LGPL (and of course the whole set of weak copyleft stuff on the resulting binary library). But I'm not a lawyer and don't really understand legalese.

#### Fragility
Uh... To be honest, `gdk-window-hack.c` already looks scary enough and the problem has been there since the beginning.
Using multiple versions of GTK during the build would result in an interesting set of issues with conflicting symbols, file dependencies, etc... I had that experience once and it wasn't solvable within the same linker namespace.
Also, as a package maintainer for binary distribution I wouldn't want anyone to deal with build process that downloads multiple versions of GTK sources.

I guess manually following gtk changes is a most reasonable approach, however inconvenient it is. GTK3 is not supposed to be heavily developed or refactored.
It might be possible to offload part of the work to users by using assertions like
```C
assert(gtk_api_to_get_ptr_to_some_known_impl_member(gdk_window) == &((GdkWindowImpl*) gdk_window)->some_known_impl_member);
```
for all important structures.
#### Users
I see 3 related bug reports for [waybar](https://github.com/Alexays/Waybar). I guess that makes it 4 concerned users of waybar including me :smile:. Yep, that's not a lot.

I have no stats for other projects using gtk-layer-shell, but I guess [wf-shell](https://github.com/WayfireWM/wf-shell) would suffer from the same issues.

And I see that Mir has a `// TODO` as xdg_popup::grab implementation. Yep, definitely not the most important issue for Mir.

**Comment by wmww** [comment]
> `gdk-window-hack.c` already looks scary enough

It actually only depends on a few things near the top of structures, which are unlikely to change. That being said, it would be nice to improve it.

The layout of `_GdkWaylandSurface` [changed 3 months ago](https://gitlab.gnome.org/GNOME/gtk/-/commit/5425edff8282ac965888468aff31470d13ce8cd8). I'm not sure if that will break the library in it's current state (I don't *think* it will), but it's an indication your patch is probably going to break sooner or later. This problem has nerd-sniped me, and it looks like I'm going to solve it now.

My plan is to have a different repo which contains the LGPL header-only library and the code to build it. The header will be committed to git so maintainers only have to pull it, not build it (although building it shouldn't be that hard either). Rather than exposing the raw structures, it will expose a bunch of methods like `xdg_surface* gdk_wayland_surface_priv_get_xdg_surface(GdkWaylandSurface*)` (or whatever it is we need). These functions will dynamically check the GTK version and switch on that. It's gunna be great!

**Comment by wmww** [comment]
I made a bunch of progress on my idea, but then I realized distro patches are pretty common for GTK, and might cause problems. Still thinking about the problem, especially my earlier idea of offloading popup management onto GTK. If I could get that to work, I could eliminate a lot of the complexity in this library. Not sure how much monkey-patching that will need.

**Comment by wmww** [comment]
It doesn't look like distro patches effect the code we care about in practice. I've moved forward with my idea and seem to have something work. Expect it to be merged and added to a new release in the coming week(s).
